adogt/adogt/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import (
    SignUpView,AdopterCreateView,profile, ShelterCreateView, CreateAdopterPreference, adopter_pref,
    AdopterProfileUpdateView, CreateShelterOffer,BrowseOfferView, OfferDetailView
)
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    path('create/adopter/<int:pk>',AdopterCreateView.as_view(),name='adopter-create'),
    path('create/shelter/<int:pk>',ShelterCreateView.as_view(),name='shelter-create'),
    path('profile/',profile,name='profile'),
    path('profile/create/pref/',CreateAdopterPreference.as_view(),name='create-pref'),
    path('profile/pref/',adopter_pref,name='adopter-pref'),
    path('profile/create/offer',CreateShelterOffer.as_view(),name='create-offer'),
    path('offers/',BrowseOfferView.as_view(),name='browse-offers'),
    path('offers/<int:pk>',OfferDetailView.as_view(),name='offer-detail'),


    path('profile/update/<int:pk>',AdopterProfileUpdateView.as_view(),name='profile-update'),#!!!!!!!!!!!!

    # path('create/pref/',CreateAdopterPreference.as_view(),name='adopter-pref'),


    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adogt/base/urls.py
from django.urls import path
from . import views

app_names = 'base'

urlpatterns = [
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
]

adogt/base/models.py
from django.db import models
from users.models import Adopter, Shelter


class Offer(models.Model):
    '''
    Creates an offer for a Shelter user.
    '''
    owner = models.ForeignKey(Shelter, on_delete=models.CASCADE, null=True)

    date_published = models.DateTimeField(auto_now_add=True)

    name = models.CharField(max_length=15,verbose_name="Dog's name",null=True)
    age = models.PositiveIntegerField(null=True)
    breed = models.CharField(max_length=20,null=True)
    SEX_CHOICE = [
        ('MALE', 'male'),
        ('FEMALE', 'female'),

    ]
    sex = models.CharField(max_length=7, choices=SEX_CHOICE,null=True)
    weight = models.PositiveIntegerField(null=True)
    sheltered_date = models.DateTimeField(verbose_name='Sheltered on ',null=True)
    found = models.CharField(max_length=30, verbose_name='Found',null=True)

    TRUE_FALSE_CHOICE = [
        (True,'Yes'),
        (False,'No'),
    ]

    is_apartment_friendly = models.BooleanField(verbose_name='Adapts well to apartment living', null=True, choices = TRUE_FALSE_CHOICE)
    is_family_friendly = models.BooleanField(verbose_name='Family friendly', null=True, choices = TRUE_FALSE_CHOICE)
    is_kid_friendly = models.BooleanField(verbose_name='Kid friendly', null=True, choices = TRUE_FALSE_CHOICE)
    is_dog_friendly = models.BooleanField(verbose_name='Dog friendly', null=True, choices = TRUE_FALSE_CHOICE)

    ENERGY_LEVELS = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
    ]
    energy_level = models.CharField(verbose_name='Energy level', choices=ENERGY_LEVELS, null=True, max_length=10)
    is_good_for_beginners = models.BooleanField(verbose_name='Good for beginners', null=True, choices = TRUE_FALSE_CHOICE)
    desc = models.TextField(max_length=200,verbose_name='Description',null=True)

    def __str__(self):
        return f"offer/{self.owner} on {self.date_published}"

class Preference(models.Model):
    owner = models.OneToOneField(Adopter,on_delete=models.CASCADE)

    age = models.PositiveIntegerField(verbose_name='Animal age')
    breed = models.CharField(max_length=20)
    SEX_CHOICE = [
        ('MALE', 'male'),
        ('FEMALE', 'female'),

    ]
    sex = models.CharField(max_length=7, choices=SEX_CHOICE)
    weight = models.PositiveIntegerField()
    found = models.CharField(max_length=30, verbose_name='Found')

    is_apartment_friendly = models.BooleanField(verbose_name='Adapts well to apartment living', null=True)
    is_family_friendly = models.BooleanField(verbose_name='Family friendly', null=True)
    is_kid_friendly = models.BooleanField(verbose_name='Kid friendly', null=True)
    is_dog_friendly = models.BooleanField(verbose_name='Dog friendly', null=True)

    ENERGY_LEVELS = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
    ]
    energy_level = models.CharField(verbose_name='Energy level', choices=ENERGY_LEVELS, null=True, max_length=10)
    is_good_for_beginners = models.BooleanField(verbose_name='Good for beginners', null=True)

    def __str__(self):
        return f"pref/{self.owner.adopter_name}"

adogt/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

class UserManager(BaseUserManager):
    '''
    User model manager where you can identify users by their email.
    '''

    def create_user(self, email,role, password, **extra_fields):
        '''
        Create and save a User using email,username and password
        '''
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, role=role, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser using email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, ('SHELTER','Shelter'),password, **extra_fields) # I know, this line hurts,
        # but the toughest decisions require the strongest will

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=30, null=True,verbose_name='Your name/Shelter name')

    ROLES = [
        ('ADOPTER','I want to adopt'),
        ('SHELTER','Shelter'),
    ]
    role = models.CharField(max_length=8,choices=ROLES[:2],verbose_name='How will you use the website?',null=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    is_adopter = models.BooleanField(default=False)
    is_shelter = models.BooleanField(default=False)

    def __str__(self):
        return self.email


class Adopter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='adopters')

    adopter_name = models.CharField(verbose_name='Your name', max_length=30, null=True)
    location = models.CharField(max_length=30, null=True)
    age = models.PositiveIntegerField(null=True)


    is_adopter = models.BooleanField(default=True)




    def __str__(self):
        return self.user.email

class Shelter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    shelter_name = models.CharField(verbose_name='Shelter name',max_length=30,null=True)
    location = models.CharField(max_length=30, null=True)
    website = models.CharField(max_length=30, null=True)
    phone_number = models.CharField(max_length=9, null=True)

    is_shelter = models.BooleanField(default=True)
    def __str__(self):
        return self.user.email

adogt/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms import ModelForm
from base.models import Preference, Offer


from .models import User, Adopter, Shelter

class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [ 'email','password1', 'password2','role']
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        print(user.is_adopter)
        print(user.role)
        if user.role == 'ADOPTER':
            user.is_adopter = True
            user.save()
            print("stworzono ADOPTERA")
            adopter = Adopter.objects.create(user=user)
            return user
        elif user.role == 'SHELTER':
            user.is_shelter = True
            user.save()
            print("stworzono SHELTER")
            shelter = Shelter.objects.create(user=user)
            return user


class PreferenceForm(ModelForm):
    class Meta:
        model = Preference
        exclude = ('owner',)
        #fields = '__all__'

class OfferForm(ModelForm):
    class Meta:
        model = Offer
        exclude = ('owner','sheltered_date')

adogt/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, FormView,UpdateView, ListView, DetailView
from django.contrib.auth import login
from .forms import SignUpForm, PreferenceForm, OfferForm
from .models import User, Adopter, Shelter
from base.models import Preference, Offer
from django.urls import reverse_lazy


class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'users/signup_form.html'

    # def get_context_data(self, **kwargs):
    #     kwargs['user_type'] = 'buyer'
    #     return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        if user.is_adopter:
            return redirect('adopter-create',pk=Adopter.objects.filter(user=user).first().pk)
        if user.is_shelter:
            return redirect('shelter-create',pk=Shelter.objects.filter(user=user).first().pk)



class AdopterCreateView(UpdateView):
    '''
    Creates Adopter profile, or in practice, updates blank fields on already existing model Adopter.
    '''
    model = Adopter
    fields = ['adopter_name','age','location']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('profile')


class ShelterCreateView(UpdateView):
    '''
    Creates Adopter profile, or in practice, updates blank fields on already existing model Adopter.
    '''
    model = Shelter
    fields = ['shelter_name','location','website','phone_number']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('profile')

def profile(request) :
    context = {
        'adopter': Adopter.objects.filter(user=request.user).first(),
        'shelter': Shelter.objects.filter(user=request.user).first(),

    }

    return render(request,'base/profile.html',context)


# class AdopterProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Adopter
#     fields = '__all__'
#
#     def form_valid(self, form):
#         form.instance.adopter_name = Adopter.objects.filter(user=self.request.user).first().adopter_name
#         form.instance.location = Adopter.objects.filter(user=self.request.user).first().location
#         form.instance.age = Adopter.objects.filter(user=self.request.user).first().age
#         return super().form_valid(form)
#
#     def test_func(self):
#         prof = self.get_object()
#         if self.request.user == prof. Adopter.objects.filter(user=self.request.user).first().adopter_name:
#             return True
#         return False

class AdopterProfileUpdateView(UpdateView):
    model = Adopter
    fields = '__all__'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # def form_valid(self, form):
    #     form.instance.adopter_name = Adopter.objects.filter(user=self.request.user).first().adopter_name
    #     form.instance.location = Adopter.objects.filter(user=self.request.user).first().location
    #     form.instance.age = Adopter.objects.filter(user=self.request.user).first().age
    #     return super().form_valid(form)
    #
    # def test_func(self):
    #     prof = self.get_object()
    #     if self.request.user == prof. Adopter.objects.filter(user=self.request.user).first().adopter_name:
    #         return True
    #     return False




class CreateAdopterPreference(CreateView):
    model = Adopter
    form_class = PreferenceForm
    template_name = 'users/create_adopter_pref.html'

    def form_valid(self, form):
        pref = form.save(commit=False)
        pref.owner = Adopter.objects.filter(user=self.request.user).first()
        pref.save()
        return redirect('profile')


def adopter_pref(request):
    context = {
        'adopter': Adopter.objects.filter(user=request.user).first(),
        'shelter': Shelter.objects.filter(user=request.user).first(),
        'pref':Preference.objects.filter(owner__user__email=request.user).first()

    }
    return render(request,'users/adopter_pref.html',context)



class CreateShelterOffer(CreateView):
    model = Shelter
    form_class = OfferForm
    template_name = 'users/create_shelter_offer.html'

    def form_valid(self, form):
        pref = form.save(commit=False)
        pref.owner = Shelter.objects.filter(user=self.request.user).first()
        pref.save()
        return redirect('profile')

class BrowseOfferView(ListView):
    model = Offer
    template_name = 'base/browse_offers.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'offers'
    #ordering = ['-date_posted']

class OfferDetailView(DetailView):
    model = Offer

adogt/users/templates/users/adopter_pref.html
{% extends 'base/main.html' %}

{% block content %}

   <h1>ADOPTER PREF</h1>

   {{ pref.sex }}


{% endblock content %}

adogt/users/templates/users/adopter_update_form.html
{% extends 'base/main.html' %}
{% load static%}

{% block style_link %}
<link rel="stylesheet" href="{% static 'base/signup_style.css' %}">
{% endblock style_link %}


{% block content %}



<form method="POST">
        {% csrf_token %}
        <div class="container mt-5">
            <div class="row">
                <div id="box" class="col-md-5 mx-auto">
                    <h1 style="text-align: center; font-size: xx-large;padding-top:10px;">Tell us about yourself</h1>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_adopter_name">Your name: </label>
                            <input input type="text" name="adopter_name"
                            required id="id_adopter_name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_age">Age:</label>
                            <input input type="number" name="age" min="0" required id="id_age" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_location">Location:</label>
                            <input input type="text" name="location" maxlength="30" required
                            id="id_location" class="form-control">
                            <!-- <span class="helptext">Enter the same password as before, for verification.</span> -->
                        </div>


                        <div class='row'>
                            <div class='col-12'>
                                <button type="submit" class="btn btn-2 btn-lg"> Save </button>
                            </div>
                            <div>
                    </form>

                </div>
            </div>
        </div>









<!--    <form method="post">{% csrf_token %}-->
<!--        {{ form.as_p }}-->
<!--        <input type="submit" value="Save">-->
<!--    </form>-->

{% endblock content%}

adogt/users/templates/users/create_adopter_pref.html
{% extends 'base/main.html' %}
{% load static%}
{% block style_link %}
<link rel="stylesheet" href="{% static 'base/signup_style.css' %}">

{% endblock style_link %}

{% block content %}


 <form method="POST">
        {% csrf_token %}
        <div class="container mt-5">
            <div class="row">
                <div id="box" class="col-md-5 mx-auto">
                    <h1 style="text-align: center;">Fill form</h1>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_age">Age:</label>
                            <input type="number" name="age" min="0" required id="id_age" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_breed">Breed:</label>
                            <input type=input type="text" name="breed" maxlength="20" required id="id_breed" class="form-control">

                        </div>
                        <p><label for="id_sex">Sex:</label> <select name="sex" required id="id_sex" class="form-control">
                            <option value="" selected>---------</option>

                            <option value="MALE">male</option>

                            <option value="FEMALE">female</option>
                        </select></p>
                        <div class="form-group">
                            <label for="id_weight">Weight:</label>
                            <input input type="number" name="weight" min="0" required id="id_weight" class="form-control">

                        </div>
                        <div class="form-group">
                            <label for="id_found">Found:</label>
                            <input input type="text" name="found" maxlength="30" required id="id_found" class="form-control">

                        </div>
                        <p><label for="id_is_apartment_friendly">Adapts well to apartment living:</label> <select class="form-control" name="is_apartment_friendly"
                            id="id_is_apartment_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_family_friendly">Family friendly:</label> <select class="form-control" name="is_family_friendly"
                            id="id_is_family_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_kid_friendly">Kid friendly:</label> <select class="form-control" name="is_kid_friendly" id="id_is_kid_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_dog_friendly">Dog friendly:</label> <select class="form-control" name="is_dog_friendly" id="id_is_dog_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_energy_level">Energy level:</label> <select class="form-control" name="energy_level" required id="id_energy_level">
                            <option value="" selected>---------</option>

                            <option value="LOW">Low</option>

                            <option value="MEDIUM">Medium</option>

                            <option value="HIGH">High</option>

                        </select></p>
                    <p><label for="id_is_good_for_beginners">Good for beginners:</label> <select class="form-control" name="is_good_for_beginners"
                            id="id_is_good_for_beginners">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>


                    </form>


                        <div class='row'>
                            <div class='col-12'>
                                <button type="submit" class="btn btn-2 btn-lg"> Save </button>
                            </div>
                            <div>
                    </form>

                </div>
            </div>
        </div>

<!--    <form method="POST">-->
<!--        {% csrf_token %}-->

<!--        {{ form.as_p}}-->

<!--        <div>-->
<!--            <button type="submit">Save</button>-->
<!--        </div>-->
<!--    </form>-->


{% endblock content %}

adogt/users/templates/users/create_shelter_offer.html
{% extends 'base/main.html' %}
{% load static %}

{% block style_link %}
<link rel="stylesheet" href="{% static 'base/signup_style.css' %}">
{% endblock style_link %}


{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="container mt-5">
            <div class="row">
                <div id="box" class="col-md-5 mx-auto">
                    <h1 style="text-align: center;">Fill form</h1>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_name">Dog's name: </label>
                            <input input type="text" name="name" maxlength="15" required id="id_name"
                                class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_age">Age:</label>
                            <input type="number" name="age" min="0" required id="id_age" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_breed">Breed:</label>
                            <input type=input type="text" name="breed" maxlength="20" required id="id_breed" class="form-control">

                        </div>
                        <p><label for="id_sex">Sex:</label> <select name="sex" required id="id_sex" class="form-control">
                            <option value="" selected>---------</option>

                            <option value="MALE">male</option>

                            <option value="FEMALE">female</option>
                        </select></p>
                        <div class="form-group">
                            <label for="id_weight">Weight:</label>
                            <input input type="number" name="weight" min="0" required id="id_weight" class="form-control">

                        </div>
                        <div class="form-group">
                            <label for="id_found">Found:</label>
                            <input input type="text" name="found" maxlength="30" required id="id_found" class="form-control">

                        </div>
                        <p><label for="id_is_apartment_friendly">Adapts well to apartment living:</label> <select class="form-control" name="is_apartment_friendly"
                            id="id_is_apartment_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_family_friendly">Family friendly:</label> <select class="form-control" name="is_family_friendly"
                            id="id_is_family_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_kid_friendly">Kid friendly:</label> <select class="form-control" name="is_kid_friendly" id="id_is_kid_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_is_dog_friendly">Dog friendly:</label> <select class="form-control" name="is_dog_friendly" id="id_is_dog_friendly">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                    <p><label for="id_energy_level">Energy level:</label> <select class="form-control" name="energy_level" required id="id_energy_level">
                            <option value="" selected>---------</option>

                            <option value="LOW">Low</option>

                            <option value="MEDIUM">Medium</option>

                            <option value="HIGH">High</option>

                        </select></p>
                    <p><label for="id_is_good_for_beginners">Good for beginners:</label> <select class="form-control" name="is_good_for_beginners"
                            id="id_is_good_for_beginners">
                            <option value="unknown" selected>Unknown</option>

                            <option value="true">Yes</option>

                            <option value="false">No</option>

                        </select></p>
                        <p><label for="id_desc">Description:</label> <textarea name="desc" cols="40" rows="10" maxlength="200" required
                            id="id_desc" class="form-control">
                    </textarea></p>

                    </form>


                        <div class='row'>
                            <div class='col-12'>
                                <button type="submit" class="btn btn-2 btn-lg"> Save </button>
                            </div>
                            <div>
                    </form>

                </div>
            </div>
        </div>

<!--    <form method="POST">-->
<!--        {% csrf_token %}-->

<!--        {{ form.as_p }}-->

<!--        <div>-->
<!--            <button type="submit">Save</button>-->
<!--        </div>-->
<!--    </form>-->


{% endblock content %}

adogt/users/templates/users/shelter_update_form.html
{% extends 'base/main.html' %}
{% load static%}

{% block style_link %}
<link rel="stylesheet" href="{% static 'base/signup_style.css' %}">
{% endblock style_link %}

{% block content %}
<form method="POST">
        {% csrf_token %}
        <div class="container mt-5">
            <div class="row">
                <div id="box" class="col-md-5 mx-auto">
                    <h1 style="text-align: center; font-size: xx-large;padding-top:10px;">Tell us about shelter</h1>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_shelter_name">Shelter name: </label>
                            <input input type="text" name="shelter_name" maxlength="30" required id="id_shelter_name"  class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_location">Location:</label>
                            <input type="text" name="location" maxlength="30" required id="id_location" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_website">Website:</label>
                            <input type="text" name="website" maxlength="30" required id="id_website" class="form-control">

                        </div>
                        <div class="form-group">
                            <label for="id_phone_number">Phone number:</label>
                            <input type="text" name="phone_number" maxlength="9" required id="id_phone_number" class="form-control">

                        </div>


                        <div class='row'>
                            <div class='col-12'>
                                <button type="submit" value="Update" class="btn btn-2 btn-lg"> Save </button>
                            </div>
                            <div>
                    </form>

                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
        </script>
        <script src="app.js"></script>

<!--    <form method="post">{% csrf_token %}-->
<!--        {{ form.as_p }}-->
<!--        <input type="submit" value="Update">-->
<!--    </form>-->

{% endblock content%}